2025-05-09 15:54:02,944 INFO    MainThread:223849 [wandb_setup.py:_flush():68] Current SDK version is 0.19.10
2025-05-09 15:54:02,944 INFO    MainThread:223849 [wandb_setup.py:_flush():68] Configure stats pid to 223849
2025-05-09 15:54:02,944 INFO    MainThread:223849 [wandb_setup.py:_flush():68] Loading settings from /home/gpuadmin/.config/wandb/settings
2025-05-09 15:54:02,944 INFO    MainThread:223849 [wandb_setup.py:_flush():68] Loading settings from /home/gpuadmin/UM_CISC7404_Reinforcement_gym_game/wandb/settings
2025-05-09 15:54:02,944 INFO    MainThread:223849 [wandb_setup.py:_flush():68] Loading settings from environment variables
2025-05-09 15:54:02,944 INFO    MainThread:223849 [wandb_init.py:setup_run_log_directory():724] Logging user logs to /home/gpuadmin/UM_CISC7404_Reinforcement_gym_game/wandb/run-20250509_155402-a06zppg8/logs/debug.log
2025-05-09 15:54:02,944 INFO    MainThread:223849 [wandb_init.py:setup_run_log_directory():725] Logging internal logs to /home/gpuadmin/UM_CISC7404_Reinforcement_gym_game/wandb/run-20250509_155402-a06zppg8/logs/debug-internal.log
2025-05-09 15:54:02,944 INFO    MainThread:223849 [wandb_init.py:init():852] calling init triggers
2025-05-09 15:54:02,944 INFO    MainThread:223849 [wandb_init.py:init():857] wandb.init called with sweep_config: {}
config: {'wandb_mode': 'online', 'entity': '', 'project': 'sac', 'alg_name': 'soft actor-critic', 'env_name': 'SkittlesEasy', 'seed': 42, 'obs_dim': (128, 128, 3), 'action_dim': 5, 'learning_rate': 0.0001, 'clip_eps': 0.2, 'buffer_size': 10000, 'batch_size': 512, 'gamma': 0.99, 'tau': 0.005, 'alpha': 0.1, 'auto_entropy_tuning': True, 'target_entropy': np.float64(1.5772491541854183), 'num_episodes': 1000, 'eval_interval': 10, 'warmup_steps': 1000, '_wandb': {}}
2025-05-09 15:54:02,945 INFO    MainThread:223849 [wandb_init.py:init():893] starting backend
2025-05-09 15:54:02,945 INFO    MainThread:223849 [wandb_init.py:init():897] sending inform_init request
2025-05-09 15:54:02,950 INFO    MainThread:223849 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-05-09 15:54:02,950 INFO    MainThread:223849 [wandb_init.py:init():907] backend started and connected
2025-05-09 15:54:02,953 INFO    MainThread:223849 [wandb_init.py:init():1002] updated telemetry
2025-05-09 15:54:02,957 INFO    MainThread:223849 [wandb_init.py:init():1026] communicating run to backend with 90.0 second timeout
2025-05-09 15:54:03,991 INFO    MainThread:223849 [wandb_init.py:init():1101] starting run threads in backend
2025-05-09 15:54:04,082 INFO    MainThread:223849 [wandb_run.py:_console_start():2566] atexit reg
2025-05-09 15:54:04,083 INFO    MainThread:223849 [wandb_run.py:_redirect():2414] redirect: wrap_raw
2025-05-09 15:54:04,083 INFO    MainThread:223849 [wandb_run.py:_redirect():2483] Wrapping output streams.
2025-05-09 15:54:04,083 INFO    MainThread:223849 [wandb_run.py:_redirect():2506] Redirects installed.
2025-05-09 15:54:04,083 INFO    MainThread:223849 [wandb_init.py:init():1147] run started, returning control to user process
2025-05-09 16:01:30,258 WARNING MsgRouterThr:223849 [router.py:message_loop():63] [no run ID] message_loop has been closed
Traceback (most recent call last):
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/router_sock.py", line 27, in _read_message
    return self._sock_client.read_server_response(timeout=1)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 235, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 220, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/router.py", line 56, in message_loop
    msg = self._read_message()
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/router_sock.py", line 29, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-05-09 16:01:30,259 INFO    MsgRouterThr:223849 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 1 handles.
2025-05-09 16:01:30,267 ERROR   MainThread:223849 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-09 16:01:30,269 ERROR   MainThread:223849 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-09 16:01:30,270 ERROR   MainThread:223849 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-09 16:01:30,270 ERROR   MainThread:223849 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-09 16:01:30,270 ERROR   MainThread:223849 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-09 16:01:30,270 ERROR   MainThread:223849 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-09 16:01:30,270 ERROR   MainThread:223849 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-09 16:01:30,270 ERROR   MainThread:223849 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-09 16:01:30,271 ERROR   MainThread:223849 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-09 16:01:30,271 ERROR   MainThread:223849 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-09 16:01:30,271 ERROR   MainThread:223849 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-09 16:01:30,271 ERROR   MainThread:223849 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-09 16:01:30,271 ERROR   MainThread:223849 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-09 16:01:30,272 ERROR   MainThread:223849 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-09 16:01:30,272 ERROR   MainThread:223849 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-09 16:01:30,272 ERROR   MainThread:223849 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-09 16:01:30,272 ERROR   MainThread:223849 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-09 16:01:30,272 ERROR   MainThread:223849 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-09 16:01:30,272 ERROR   MainThread:223849 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-09 16:01:30,272 ERROR   MainThread:223849 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-09 16:01:30,273 ERROR   MainThread:223849 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-09 16:01:30,273 ERROR   MainThread:223849 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-09 16:01:30,273 ERROR   MainThread:223849 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-09 16:01:30,273 ERROR   MainThread:223849 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-09 16:01:30,273 ERROR   MainThread:223849 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-09 16:01:30,273 ERROR   MainThread:223849 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-09 16:01:30,273 ERROR   MainThread:223849 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-09 16:01:30,274 ERROR   MainThread:223849 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-09 16:01:30,274 ERROR   MainThread:223849 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-09 16:01:30,274 ERROR   MainThread:223849 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-09 16:01:30,274 ERROR   MainThread:223849 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-09 16:01:30,274 ERROR   MainThread:223849 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-09 16:01:30,274 ERROR   MainThread:223849 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-09 16:01:30,274 ERROR   MainThread:223849 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-09 16:01:30,274 ERROR   MainThread:223849 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-09 16:01:30,274 ERROR   MainThread:223849 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-09 16:01:30,275 ERROR   MainThread:223849 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-09 16:01:30,275 ERROR   MainThread:223849 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-09 16:01:30,275 ERROR   MainThread:223849 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-09 16:01:30,275 ERROR   MainThread:223849 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
